from __future__ import annotations

import argparse
import difflib
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

LINK_RE = re.compile(r"(!?)\[([^\]]*)\]\(([^)]+)\)")
IPYNB_TARGET_RE = re.compile(r"^([^#]+)\.ipynb(#.*)?$")


def _nbconvert():
    try:
        import nbformat
        from nbconvert import MarkdownExporter
        from nbconvert.preprocessors import TagRemovePreprocessor
        from traitlets.config import Config
    except ImportError:
        print(
            "error: nbconvert/nbformat not installed. "
            "Install docs dependencies first (uv sync).",
            file=sys.stderr,
        )
        raise SystemExit(2) from None
    return nbformat, MarkdownExporter, TagRemovePreprocessor, Config


def discover_notebooks() -> list[Path]:
    return sorted(
        p for p in DOCS_DIR.rglob("*.ipynb") if ".ipynb_checkpoints" not in p.parts
    )


def make_exporter():
    nbformat, MarkdownExporter, TagRemovePreprocessor, Config = _nbconvert()
    config = Config()
    # Mirrors mkdocs.yml's mknotebooks.tag_remove_configs.
    config.TagRemovePreprocessor.remove_cell_tags = {"remove_cell"}
    config.TagRemovePreprocessor.remove_all_outputs_tags = {"remove_all_output"}
    config.TagRemovePreprocessor.remove_single_output_tags = {"remove_single_output"}
    config.TagRemovePreprocessor.remove_input_tags = {"remove_input"}
    config.TagRemovePreprocessor.enabled = True
    exporter = MarkdownExporter(config=config)
    exporter.register_preprocessor(TagRemovePreprocessor(config=config), enabled=True)
    return exporter, nbformat


def convert_notebook(exporter, nbformat, src: Path, dest: Path) -> tuple[str, dict[str, bytes]]:
    notebook = nbformat.read(src, as_version=4)
    files_dir = dest.stem + "_files"
    body, resources = exporter.from_notebook_node(
        notebook,
        resources={"metadata": {"name": dest.stem}, "output_files_dir": files_dir},
    )
    return body, resources.get("outputs", {})


def rewrite_links(body: str) -> str:
    """Swap a sibling ``*.ipynb`` link target for its generated ``*.md``.

    Every other relative link is already written relative to the page's
    rendered URL (unchanged by this conversion) and needs no adjustment.
    """

    def repl(match: re.Match[str]) -> str:
        bang, text, target = match.groups()
        m = IPYNB_TARGET_RE.match(target)
        if not m:
            return match.group(0)
        stem, anchor = m.groups()
        return f"{bang}[{text}]({stem}.md{anchor or ''})"

    return LINK_RE.sub(repl, body)


def header_for(src_relative: str) -> str:
    return (
        "<!-- AUTOGENERATED by scripts/convert_notebooks.py — DO NOT EDIT.\n"
        f"     Source: docs/{src_relative}. Outputs are committed in the\n"
        "     notebook; this conversion does not re-execute code. -->\n\n"
    )


def render(src: Path) -> tuple[Path, str, dict[str, bytes]]:
    exporter, nbformat = make_exporter()
    rel = src.relative_to(DOCS_DIR)
    dest = src.with_suffix(".md")
    body, outputs = convert_notebook(exporter, nbformat, src, dest)
    body = rewrite_links(body)
    return dest, header_for(str(rel)) + body, outputs


def write_outputs(dest: Path, files: dict[str, bytes]) -> None:
    files_dir = dest.parent / (dest.stem + "_files")
    if files_dir.exists():
        shutil.rmtree(files_dir)
    for name, data in files.items():
        target = dest.parent / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated Markdown differs from committed conversion.",
    )
    args = parser.parse_args()

    notebooks = discover_notebooks()
    if not notebooks:
        print("error: no notebooks found under docs/", file=sys.stderr)
        raise SystemExit(1)

    failures: list[str] = []
    for src in notebooks:
        dest, content, files = render(src)
        if args.check:
            existing = dest.read_text(encoding="utf-8") if dest.exists() else None
            if existing != content:
                failures.append(str(src.relative_to(DOCS_DIR)))
                diff = difflib.unified_diff(
                    (existing or "").splitlines(),
                    content.splitlines(),
                    fromfile=str(dest),
                    tofile="generated",
                    lineterm="",
                )
                print(f"stale: {src.relative_to(DOCS_DIR)} -> {dest.relative_to(REPO_ROOT)}")
                print("\n".join(list(diff)[:20]))
            continue
        dest.write_text(content, encoding="utf-8")
        write_outputs(dest, files)
        print(f" - {src.relative_to(DOCS_DIR)} -> {dest.relative_to(REPO_ROOT)}")

    if failures:
        print(
            "\nerror: generated pages are stale. "
            "Run 'python scripts/convert_notebooks.py' and commit the result.",
            file=sys.stderr,
        )
        raise SystemExit(1)


if __name__ == "__main__":
    main()
