[project]
name = "arakawa-docs"
version = "0.0.0"
description = "Arakawa Docs"
requires-python = ">=3.10"
authors = []
dependencies = [
    "arakawa[plotting]",
    "mkdocs-redirects>=1.2.2",
    "mkdocstrings[python]>=0.27.0",
    "mkdocs-material>=9.5.45",
    "mknotebooks>=0.8.0,<0.9.0",
    "jupyterlab>=4.3.0",
    "seaborn>=0.13.2",
    "openpyxl>=3.1.5",
    "pandas-datareader>=0.10.0,<0.11.0",
    "pytrends>=4.9.2",
    "nltk>=3.9.1",
    "vega-datasets>=0.9.0",
    "nbstripout>=0.8.1",
]

[tool.uv.sources]
arakawa = { path = "../python-client" }
