[project]
name = "arakawa-docs"
version = "0.0.0"
description = "Arakawa Docs"
requires-python = ">=3.11"
authors = []
dependencies = [
    "arakawa[all]",
    "bokeh-sampledata>=2025.0",
    "jupyterlab>=4.4.2",
    "mdx-truly-sane-lists>=1.3",
    "mike>=2.2.0",
    "mkdocs-material>=9.7.7",
    "mkdocs-redirects>=1.2.3",
    "mkdocstrings[python]>=1.0.6",
    "nbconvert>=7.17.1",
    "nbformat>=5.11.1",
    "nbstripout>=0.9.1",
    "nltk>=3.10.3",
    "openpyxl>=3.1.5",
    "packaging>=26.3",
    "pandas-datareader>=0.11.1",
    "pytrends>=4.9.2",
    "seaborn>=0.13.2",
    "vega-datasets>=0.9.0",
    "zensical",
]

[tool.uv.sources]
arakawa = { path = "../python-client" }
mike = { git = "https://github.com/squidfunk/mike.git", rev = "2d4ad799442f4592db8ad53b179bfb33db8c69ac" }
