version: "3"

tasks:
  reinstall-arakawa:
    cmd: uv sync --reinstall-package arakawa
  build-notebooks:
    cmd: ./nbbuild.sh
  clear-notebooks:
    cmd: ./nbclear.sh
  serve:
    cmd: mkdocs serve
    deps:
      - reinstall-arakawa
      - build-notebooks
  build:
    cmd: mkdocs build
    deps:
      - reinstall-arakawa
      - build-notebooks
