name: Build (test)

on:
  workflow_dispatch:

jobs:
  npm-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web-components/package-lock.json
      - run: npm install
      - run: npm run build
      # build local report
      - run: npm run build:local-report
      # upload local report assets
      - uses: actions/upload-artifact@v4
        with:
          name: local-report-css
          path: ./web-components/dist/local-report/local-report.css
      - uses: actions/upload-artifact@v4
        with:
          name: local-report-js
          path: ./web-components/dist/local-report/local-report.js
  pypi-build:
    needs: [npm-build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - run: pip install -r requirements.txt
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-3.11-${{ hashFiles('uv.lock') }}
      - run: uv sync --frozen --all-extras
      # download local report assets
      - uses: actions/download-artifact@v4
        with:
          path: ./src/arakawa/resources/html_templates/
          pattern: local-report-*
          merge-multiple: true
      - run: uv run pyproject-build
