name: Publish docs

on:
  workflow_dispatch:
    inputs:
      arVersion:
        description: "AR version"
        required: true
        type: string

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # zizmor: ignore[artipacked]
          fetch-depth: 0 # fetch all commits/branches
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/uv
          key: uv-3.13-${{ hashFiles('uv.lock') }}
      - run: uv sync --frozen
      - name: Reinstall from ../python-client
        run: uv sync --reinstall-package arakawa
      - run: AR_VERSION=${INPUTS_ARVERSION} ./nbbuild.sh
        env:
          INPUTS_ARVERSION: ${{ inputs.arVersion }}
      - run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          VERSION=$(uv run python convert_to_py_version.py "${INPUTS_ARVERSION}")
          if echo "$VERSION" | grep -q "[A-Za-z]"; then
            echo "beta/alpha version detected"
            uv run mike deploy "$VERSION" --update-aliases --push
          else
            echo "stable version detected"
            uv run mike deploy "$VERSION" latest --update-aliases --push
            uv run mike set-default --push latest
          fi
        env:
          INPUTS_ARVERSION: ${{ inputs.arVersion }}
