name: Publish docs

on:
  workflow_dispatch:
    inputs:
      arVersion:
        description: "AR version"
        required: true
        type: string

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - run: pip install -r requirements.txt
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-3.11-${{ hashFiles('uv.lock') }}
      - run: uv sync --frozen
      - name: Reinstall from ../python-client
        run: uv sync --reinstall-package arakawa
      - run: AR_VERSION=${{ inputs.arVersion }} ./nbbuild.sh
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: |
          VERSION=$(python convert_to_py_version.py ${{ inputs.arVersion }})
          if echo $VERSION | grep -q "[A-Za-z]"; then
            uv run mike deploy $VERSION --update-aliases --push
          else
            uv run mike deploy $VERSION latest --update-aliases --push
          fi
