name: Publish packages & docs

on:
  release:
    types: ["created"]

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web-components/package-lock.json
      - run: npm install
      - run: npm run build
      - run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: ./web-components
          token: ${{ secrets.NPM_TOKEN }}
      # build local report
      - run: npm run build:local-report
      # upload local report assets
      - uses: actions/upload-artifact@v4
        with:
          name: local-report-css
          path: ./web-components/dist/local-report/local-report.css
      - uses: actions/upload-artifact@v4
        with:
          name: local-report-js
          path: ./web-components/dist/local-report/local-report.js
  publish-pypi-package:
    needs: [publish-npm-package]
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    defaults:
      run:
        working-directory: ./python-client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: "pip"
      - run: pip install -r requirements.txt
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-3.13-${{ hashFiles('uv.lock') }}
      - run: uv sync --frozen --all-extras
      # download local report assets
      - uses: actions/download-artifact@v4
        with:
          path: ./python-client/src/arakawa/resources/html_templates/
          pattern: local-report-*
          merge-multiple: true
      # confirm local report assets are present
      - run: |
          test -e ./src/arakawa/resources/html_templates/local-report.css
          test -e ./src/arakawa/resources/html_templates/local-report.js
      - run: uv build
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # NOTE: need to use absolute path since working-directory is not respected...
          packages-dir: ./python-client/dist/
  publish-docs:
    needs: [publish-npm-package, publish-pypi-package]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-3.13-${{ hashFiles('uv.lock') }}
      - run: uv sync --frozen --all-extras
      - name: Reinstall from ../python-client
        run: uv sync --reinstall-package arakawa
      - run: AR_VERSION=${{ github.event.release.tag_name }} ./nbbuild.sh
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      # NOTE: tag name is semver
      - run: |
          VERSION=$(uv run python convert_to_py_version.py "${{ github.event.release.tag_name }}")
          if echo "$VERSION" | grep -q "[A-Za-z]"; then
            echo "beta/alpha version detected"
            uv run mike deploy "$VERSION" --update-aliases --push
          else
            echo "stable version detected"
            uv run mike deploy "$VERSION" latest --update-aliases --push
            uv run mike set-default --push latest
          fi
